---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/nova/nova-three-cells/edpm/nodeset

resources:
  - values.yaml
  - nova_cell2_service.yaml

patches:
  - target:
      kind: OpenStackDataPlaneNodeSet
      name: openstack-edpm
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack-edpm-2
