---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../../dt/nova/nova-three-cells/edpm/deployment

resources:
  - values.yaml

patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: edpm-deployment
    patch: |
      - op: add
        path: /spec/nodeSets/-
        value: openstack-edpm-2
